### ISSUE TITLE
Perbaiki Algoritma absen masuk dan keluar 

### ISSUE THREAD

**Issue by ghost** [miftahalamsyah/siagelo#1]
public function absenKeluar(Request $request)
    {
        //Ready to use

        $guru_p3k = GuruP3K::where('id_user', auth()->user()->id)->first();

        $timezone = 'Asia/Jakarta';
        $date = new DateTime('now', new DateTimeZone($timezone));
        $tanggal = $date->format('Y-m-d');
        $localtime = $date->format('H:i:s');

        // data koordinat sekolah
        $koord = Koordinat::where('id', 1)->first();

        $jarak = $this->distance($request->lat, $request->lng, $koord->latitude, $koord->longitude, "K"); // <-- dihitung menggunakan satuan kilometer

        $p3k_absen = GuruP3KAbsen::where('id_guru_p3k', '=', $guru_p3k->id)->where('tgl', '=', $tanggal)->first();

        if ($p3k_absen) {
            if ($p3k_absen->jam_keluar == "") {
                if ($jarak < 0.2) {

                    $p3k_absen->update([
                        'jam_keluar' => $localtime,
                        'jam_kerja' => date('H:i:s', strtotime($localtime) - strtotime($p3k_absen->jam_masuk))
                    ]);

                    Alert::success('Berhasil', 'Sampai ketemu lagi besok :)');
                    return redirect('/absen-guru-p3k');
                } else {
                    Alert::error('Gagal', 'Jarak anda jauh dari sekolah!');
                    return redirect()->back();
                }
            } else {
                Alert::warning('Peringatan', 'Sudah melakukan absensi keluar');
                return redirect()->back();
            }

**Comment by ghost** [comment]
yang anda masih 0.015 alias 15 meter saja pak. time zone diganti wib (jakarta)


$guru_pns = GuruPNS::where('id_user', auth()->user()->id)->first();

        $timezone = 'Asia/Makassar'; 
        $date = new DateTime('now', new DateTimeZone($timezone)); 
        $tanggal = $date->format('Y-m-d');
        $localtime = $date->format('H:i:s');

        // data koordinat sekolah
        $koord = Koordinat::where('id', 1)->first();

        $jarak = $this->distance($request->lat, $request->lng, $koord->latitude, $koord->longitude, "K"); // <-- dihitung menggunakan satuan kilometer

        $pns_absen = GuruPNSAbsen::where('id_guru_pns', '=', $guru_pns->id)->where('tgl', '=', $tanggal)->first();

        if($pns_absen) {
            if($pns_absen->jam_keluar == "") {
                if ($jarak < 0.015) {
                    $pns_absen->update([
                        'jam_keluar' => $localtime,
                        'jam_kerja' => date('H:i:s', strtotime($localtime) - strtotime($pns_absen->jam_masuk))
                    ]);
    
                    Alert::success('Berhasil', 'Sampai ketemu lagi besok :)');
                    return redirect('/absen-guru-pns');
                }

**Comment by miftahalamsyah** [comment]
Another day just another keluarbiasaan dari pak Johan
